"""String Recources."""
FORMAT = "%(asctime)s %(levelname)s %(name)s %(message)s"
FILE_NAME = "stout.log"
ENCODING = "utf-8"
NOT_FOUND_MSG = "File not found: {path}"
PERMISSION_MSG = "Permission denied: {path}"
IS_DIRECTORY_MSG = "Path is a directory: {path}"
PATTERN_ERROR = "error: The following required arguments were not provided:\n\t <PATTERN>\n"
PATH_ERROR = "error: The following required arguments were not provided:\n\t <PATH>\n"
UNREACHABLE_ERROR = "Unreachable, something unexpected happend."
NO_LINES_MSG = "No lines found."
